# Define all the services (containers) that make up your application

# anchor for reuse (named blob)
x-app-env: &app-env
  env_file: .env
  extra_hosts:
    - "host.docker.internal:host-gateway"
  environment:
    # overrides from .env
    DATABASE_URL: postgresql+psycopg2://todo_user:todo_password@host.docker.internal:5432/todo_db
    REDIS_HOST: host.docker.internal
    KAFKA_BOOTSTRAP_SERVERS: kafka:29092

services:
  # Main FastAPI application service
  todo-api:
    <<: *app-env            # insert values from app-env
    build: .                  # Build the image using the Dockerfile in the current directory (.)
    container_name: todo-api
    ports:
      - "8000:8000"           # Map host port 8000 to container port 8000
    restart: unless-stopped   # Auto-restart container if it crashes

  # Kafka
  kafka:
    image: apache/kafka:4.3.1
    container_name: todo-kafka
    ports:
      - "9092:9092"
    environment:
      # Unique id for this node (must match quorum voters)
      KAFKA_NODE_ID: 1
      # Combined broker + controller (OK for local; often split in prod)
      KAFKA_PROCESS_ROLES: broker,controller

      # Bind inside container: clients on 9092, controller on 9093, NAME://host:port, Plaintext: (no TLS)
      # KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

      # What host apps should use after connect
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Must match NODE_ID
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093 # nodeId@host:port

      # Single-broker local settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # if topic that producer writes to does not exist, Kafka creates it
    healthcheck: # check container is healthy
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 40s

  kafka-ui: # browser UI to inspect clusters, topics and messages
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      # From another container use service name, not localhostw
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092 # How UI container reaches Kafka
    depends_on:
      - kafka

  outbox-publisher:
    <<: *app-env
    build: .
    container_name: todo-outbox-publisher
    command: [ "python", "-m", "workers.outbox_publisher" ]
    healthcheck:
      test: ["NONE"]
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped

  event-consumer:
    <<: *app-env
    build: .
    container_name: todo-event-consumer
    command: [ "python", "-m", "workers.event_consumer" ]
    healthcheck:
      test: ["NONE"]
    depends_on:
      kafka:
        condition: service_started
    restart: unless-stopped

  # postgresql db will be connected via local:

